"""Core data models for the options trading bot."""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime


class OptionType(enum.Enum):
    CALL = "call"
    PUT = "put"


class PositionSide(enum.Enum):
    LONG = "long"
    SHORT = "short"


class OrderAction(enum.Enum):
    BUY_TO_OPEN = "buy_to_open"
    SELL_TO_OPEN = "sell_to_open"
    BUY_TO_CLOSE = "buy_to_close"
    SELL_TO_CLOSE = "sell_to_close"


class SignalType(enum.Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"


@dataclass
class OptionContract:
    """Represents a single option contract."""

    symbol: str
    option_type: OptionType
    strike: float
    expiration: datetime
    premium: float
    underlying_price: float
    implied_volatility: float = 0.0
    open_interest: int = 0
    volume: int = 0
    bid: float = 0.0
    ask: float = 0.0

    @property
    def mid_price(self) -> float:
        if self.bid > 0 and self.ask > 0:
            return (self.bid + self.ask) / 2.0
        return self.premium

    @property
    def spread(self) -> float:
        return self.ask - self.bid

    @property
    def moneyness(self) -> float:
        """Ratio of underlying price to strike. >1 means ITM for calls."""
        return self.underlying_price / self.strike

    @property
    def is_itm(self) -> bool:
        if self.option_type == OptionType.CALL:
            return self.underlying_price > self.strike
        return self.underlying_price < self.strike

    @property
    def intrinsic_value(self) -> float:
        if self.option_type == OptionType.CALL:
            return max(0.0, self.underlying_price - self.strike)
        return max(0.0, self.strike - self.underlying_price)

    @property
    def time_value(self) -> float:
        return self.premium - self.intrinsic_value


@dataclass
class GreeksResult:
    """Container for option Greeks values."""

    delta: float = 0.0
    gamma: float = 0.0
    theta: float = 0.0
    vega: float = 0.0
    rho: float = 0.0


@dataclass
class OptionLeg:
    """A single leg of an options strategy."""

    contract: OptionContract
    side: PositionSide
    quantity: int = 1

    @property
    def net_premium(self) -> float:
        """Positive = credit received, negative = debit paid."""
        multiplier = -1.0 if self.side == PositionSide.LONG else 1.0
        return multiplier * self.contract.premium * self.quantity * 100

    def pnl_at_expiry(self, underlying_price: float) -> float:
        """Calculate P&L at expiration for a given underlying price."""
        if self.contract.option_type == OptionType.CALL:
            intrinsic = max(0.0, underlying_price - self.contract.strike)
        else:
            intrinsic = max(0.0, self.contract.strike - underlying_price)

        if self.side == PositionSide.LONG:
            return (intrinsic - self.contract.premium) * self.quantity * 100
        else:
            return (self.contract.premium - intrinsic) * self.quantity * 100


@dataclass
class Signal:
    """A trading signal generated by the signal engine."""

    signal_type: SignalType
    symbol: str
    strength: float  # 0.0 to 1.0
    timestamp: datetime
    reason: str
    indicators: dict[str, float] = field(default_factory=dict)


@dataclass
class TradeOrder:
    """Represents an order to be placed."""

    legs: list[OptionLeg]
    action: OrderAction
    strategy_name: str
    signal: Signal | None = None
    timestamp: datetime = field(default_factory=datetime.now)

    @property
    def net_premium(self) -> float:
        return sum(leg.net_premium for leg in self.legs)

    @property
    def max_loss(self) -> float:
        """Estimate max loss across a range of prices."""
        if not self.legs:
            return 0.0
        strikes = [leg.contract.strike for leg in self.legs]
        test_range = range(int(min(strikes) * 0.5), int(max(strikes) * 1.5) + 1)
        return min(
            sum(leg.pnl_at_expiry(float(p)) for leg in self.legs)
            for p in test_range
        )

    @property
    def max_profit(self) -> float:
        """Estimate max profit across a range of prices."""
        if not self.legs:
            return 0.0
        strikes = [leg.contract.strike for leg in self.legs]
        test_range = range(int(min(strikes) * 0.5), int(max(strikes) * 1.5) + 1)
        return max(
            sum(leg.pnl_at_expiry(float(p)) for leg in self.legs)
            for p in test_range
        )


@dataclass
class Position:
    """An open position in the portfolio."""

    position_id: str
    legs: list[OptionLeg]
    strategy_name: str
    entry_time: datetime
    entry_premium: float
    current_value: float = 0.0
    realized_pnl: float = 0.0
    is_closed: bool = False
    close_time: datetime | None = None

    @property
    def unrealized_pnl(self) -> float:
        if self.is_closed:
            return 0.0
        return self.current_value - self.entry_premium

    @property
    def total_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl


@dataclass
class MarketSnapshot:
    """A snapshot of market data for a symbol."""

    symbol: str
    price: float
    timestamp: datetime
    high: float = 0.0
    low: float = 0.0
    open: float = 0.0
    close: float = 0.0
    volume: int = 0
    historical_volatility: float = 0.0
    iv_rank: float = 0.0  # 0-100 percentile
    iv_percentile: float = 0.0  # 0-100 percentile
